<template>
  <div class="flex flex-col flex-grow w-full overflow-y-auto custom-scrollbar">
    <!-- TITLE -->
    <Portal to="h-title">
      <h2 class="text-nile-blue dark:text-let-it-snow md:text-md 3xl:text-lg 4xl:text-xl">UBXT Info</h2>
    </Portal>

    <div class="flex flex-col flex-grow w-full overflow-y-auto custom-scrollbar">
      <AppCard
        class="ubxt-info flex flex-col flex-grow relative w-full
        p-20 md:p-30 space-y-40 md:space-y-50 overflow-y-auto custom-scrollbar"
      >
        <!-- ITEM 1 -->
        <div class="flex flex-col flex-shrink-0">
          <h2 class="ubxt-info__title">WHAT IS THE UBXT TOKEN?</h2>

          <p class="ubxt-info__desc">
            The UBXT token is a utility token that is based on the ERC20 protocol of the Ethereum blockchain.
            We created a token to allow a transparent, secure and optimized use of our application.
          </p>
        </div>

        <!-- ITEM 2 -->
        <div class="flex flex-col flex-shrink-0">
          <h2 class="ubxt-info__title">HOW CAN I USE MY UBXT?</h2>

          <div class="ubxt-info__desc flex flex-col">
            <p>
              UpBots tokens will have a central role in the platform. UBXT will be mainly used for
              <strong class="text-chicory-flower dark:text-white">
                payment of subscriptions</strong>, training courses, and for the payment of the
              <strong class="text-chicory-flower dark:text-white">
                profit success fees
              </strong> generated by an external bot or social copy trading.
            </p>
          </div>
        </div>

        <!-- ITEM 3 -->
        <div class="flex flex-col flex-shrink-0">
          <h2 class="ubxt-info__title">WHAT IS THE BURNING PROGRAM?</h2>

          <p class="ubxt-info__desc">
            The burning program is an automatic process that will ‘burn’ tokens according to the turnover,
            in order to reduce the number of tokens in circulation.
          </p>
        </div>

        <!-- ITEM 4 -->
        <div class="grid gap-rows-1 xl:gap-rows-none xl:grid-cols-2 gap-y-40 md:gap-y-60 xl:gap-y-0 xl:gap-x-70">
          <div class="flex flex-col w-full">
            <h3 class="text-chirony-flower dark:text-hidden-sea-glass text-lg font-semibold mb-20 md:mb-40">
              Performance Fee Burn
            </h3>

            <p class="text-nile-blue dark:text-blair text-md font-medium mb-30 md:mb-40">
              Depending on the performance fees chosen by the developer, up to 4.62% of the profit generated
              is converted into UBXT and burned.
            </p>

            <div class="flex flex-col items-center mt-auto">
              <div class="ubxt-info__logo-img-wrap flex">
                <img src="img/ubxt-info/upbots-logo.png" alt="ubxt-info-logo" class="w-full h-full">
              </div>
            </div>
          </div>

          <div class="flex flex-col w-full">
            <h3 class="text-chirony-flower dark:text-hidden-sea-glass text-lg font-semibold mb-20 md:mb-40">
              Annual Income Burn
            </h3>

            <p class="text-nile-blue dark:text-blair text-md font-medium mb-30 md:mb-40">
              Every first quarter of the year, a certain% of the net income will be used to burn tokens.
            </p>

            <!-- DESKTOP CIRCLE -->
            <mq-layout mq="lg+" class="flex items-end space-x-20 xl:space-x-30 mt-auto">
              <CircleInfo title="15%" desc="Q4 2021" :circle-size="'160'" :title-size="'50'" />
              <CircleInfo title="10%" desc="Q4 2022" :circle-size="'120'" :title-size="'40'" />
              <CircleInfo title="5%" desc="Q4 2023" :circle-size="'84'" :title-size="'30'" />
              <CircleInfo title="2%" desc="Q4 2024" :circle-size="'50'" :title-size="'20'" />
            </mq-layout>

            <!-- MOBILE CIRCLE -->
            <mq-layout mq="sm-md" class="flex items-end justify-between space-x-10 mt-auto">
              <CircleInfo title="15%" desc="Q4 2021" circle-size="90" title-size="26" />
              <CircleInfo title="10%" desc="Q4 2022" circle-size="65" title-size="21" />
              <CircleInfo title="5%" desc="Q4 2023" circle-size="46" title-size="16" />
              <CircleInfo title="2%" desc="Q4 2024" circle-size="27" title-size="12" />
            </mq-layout>
          </div>
        </div>
      </AppCard>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

import CircleInfo from './components/CircleInfo.vue'

export default defineComponent({
  name: 'UBXTInfo',

  components: { CircleInfo }
})
</script>

<style lang="scss" scoped>
.ubxt-info {
  &__title {
    @apply font-bold text-chicory-flower dark:text-white uppercase mb-10;
  }

  &__desc {
    @apply text-nile-blue dark:text-blair text-md font-medium;
  }

  @media (min-width: 768px) {
    &__title {
      @apply text-2xl;
    }

    &__logo-img-wrap {
      max-width: 144px;
    }
  }

  @media (min-width: 1280px) {
    &__logo-desc {
      max-width: 280px;
    }
  }

  @media (max-width: 767px) {
    &__title {
      @apply text-lg;
    }

    &__logo-img-wrap {
      max-width: 75px;
    }
  }
}
</style>
